services:
  db:
    ports:
      - "5432:5432"
    
  backend:
    ports:
      - "8000:80"
    volumes:
      - ./backend/app:/code/app
      
  frontend:
    build:
      target: dev              # ← stops at dev stage
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app        # hot reload
      # - ./frontend/node_modules:/app/node_modules
      - /node_modules:/app/node_modules
