#!/usr/bin/env bash

set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# Prefer the project venv; fall back to whatever is on PATH
if [ -f "$ROOT_DIR/.venv/bin/activate" ]; then
    source "$ROOT_DIR/.venv/bin/activate"
fi

# Load environment variables from .env
if [ -f "$ROOT_DIR/.env" ]; then
    set -a
    source "$ROOT_DIR/.env"
    set +a
fi

if [ -x "$ROOT_DIR/.venv/bin/alembic" ]; then
    ALEMBIC="$ROOT_DIR/.venv/bin/alembic"
else
    ALEMBIC="$(command -v alembic || true)"
fi

if [ -x "$ROOT_DIR/.venv/bin/python" ]; then
    PYTHON="$ROOT_DIR/.venv/bin/python"
else
    PYTHON="$(command -v python || true)"
fi

if [ -x "$ROOT_DIR/.venv/bin/pytest" ]; then
    PYTEST="$ROOT_DIR/.venv/bin/pytest"
else
    PYTEST="$(command -v pytest || true)"
fi

if [ -z "$ALEMBIC" ] || [ -z "$PYTHON" ] || [ -z "$PYTEST" ]; then
    echo "Missing required tools: alembic/python/pytest must be installed and discoverable on PATH." >&2
    exit 127
fi

# Provide DATABASE_URL for drift_check.py and pytest conftest if not already set
export DATABASE_URL="${DATABASE_URL:-}"

LOG_FILE="${DRIFT_LOG_FILE:-logs/drift_gate_local.log}"
PENDING_REV_ID="${PENDING_REV_ID:-pending_check_tmp_local}"
PENDING_MSG="${PENDING_MSG:-verify_no_pending_local_gate}"
PENDING_FILE="db/alembic/versions/${PENDING_REV_ID}_${PENDING_MSG}.py"

mkdir -p "$(dirname "$LOG_FILE")"

set +e

echo "Schema drift local run started at $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$LOG_FILE"

echo "== GATE 1: alembic upgrade head ==" >> "$LOG_FILE"
"$ALEMBIC" -c alembic.ini upgrade head >> "$LOG_FILE" 2>&1
G1=$?

echo "== GATE 2: drift_check.py ==" >> "$LOG_FILE"
"$PYTHON" db/scripts/drift_check.py >> "$LOG_FILE" 2>&1
G2=$?

echo "== GATE 3: pytest schema drift ==" >> "$LOG_FILE"
"$PYTEST" db/test/test_schema_drift.py -q --maxfail=1 --disable-warnings --tb=short --test-alembic >> "$LOG_FILE" 2>&1
G3=$?

echo "== GATE 4: pending autogenerate check ==" >> "$LOG_FILE"
"$ALEMBIC" -c alembic.ini revision --autogenerate -m "$PENDING_MSG" --rev-id "$PENDING_REV_ID" >> "$LOG_FILE" 2>&1
G4=$?

if grep -q "has no type within the model" "$LOG_FILE"; then
    TYPE_WARNINGS="$(grep "has no type within the model" "$LOG_FILE" || true)"
    echo "❌ Alembic reported model column(s) without explicit SQL type metadata." >> "$LOG_FILE"
    if [ -n "$TYPE_WARNINGS" ]; then
        printf '%s\n' "$TYPE_WARNINGS" >> "$LOG_FILE"
    fi
    G4=1
fi

if [ -f "$PENDING_FILE" ] && grep -qE "op\.(create|drop|add|alter)" "$PENDING_FILE"; then
    echo "❌ Pending schema operations detected in autogenerated migration." >> "$LOG_FILE"
    grep -E "op\.(create|drop|add|alter)" "$PENDING_FILE" >> "$LOG_FILE"
    G4=1
fi

RESULT="RESULT migration=$G1 drift_script=$G2 pytest_drift=$G3 pending_autogen=$G4"
echo "$RESULT" | tee -a "$LOG_FILE"

rm -f "$PENDING_FILE"

if [ "$G1" -ne 0 ] || [ "$G2" -ne 0 ] || [ "$G3" -ne 0 ] || [ "$G4" -ne 0 ]; then
    exit 1
fi

exit 0
