-- Reference data seed for local Docker / entrypoint-initdb.d
--
-- This script runs once on first PostgreSQL container initialization, after
-- 01_dump.sql (schema) and 02_align_alembic_revision.sql (Alembic stamp).
-- It mirrors the reference rows intended by Alembic migration 012: units,
-- allergens, and additives sourced from db/scripts/reference_data/*.json as
-- plain SQL so init does not depend on Python or JSON parsing.
--
-- Idempotent: each INSERT uses ON CONFLICT (code) DO UPDATE.

BEGIN;

-- ---------------------------------------------------------------------------
-- units (from units.json)
-- ---------------------------------------------------------------------------
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'g', 'Gramm', 'gram', 1, 'weight', true) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'kg', 'Kilogramm', 'kilogram', 1000, 'weight', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'mg', 'Milligramm', 'milligram', 0.001, 'weight', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'ml', 'Milliliter', 'milliliter', 1, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'cl', 'Zentiliter', 'centiliter', 10, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'dl', 'Deziliter', 'deciliter', 100, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'l', 'Liter', 'liter', 1000, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'el', 'Esslöffel', 'tablespoon', 15, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'tl', 'Teelöffel', 'teaspoon', 5, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'prise', 'Prise', 'pinch', 0.5, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'stk', 'Stück', 'piece', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'pck', 'Packung', 'pack', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'bund', 'Bund', 'bunch', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'dose', 'Dose', 'can', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'blatt', 'Blatt', 'leaf/sheet', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'zehe', 'Zehe', 'clove', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'scheibe', 'Scheibe', 'slice', NULL, 'piece', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;
INSERT INTO public.units (id, code, name_de, name_en, grams_per_unit, unit_type, is_base) VALUES (gen_random_uuid(), 'tasse', 'Tasse', 'cup', 240, 'volume', false) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, grams_per_unit = EXCLUDED.grams_per_unit, unit_type = EXCLUDED.unit_type, is_base = EXCLUDED.is_base;

-- ---------------------------------------------------------------------------
-- allergens (from allergens.json); code and parent_code are integers
-- ---------------------------------------------------------------------------
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 1, 'Gluten', 'Gluten (general)', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 2, 'Gluten/ Weizen', 'Gluten/ Wheat', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 3, 'Gluten/ Roggen', 'Gluten/ Rye', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 4, 'Gluten/ Gerste', 'Gluten/ Barley', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 5, 'Gluten/ Hafer', 'Gluten/ Oats', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 6, 'Gluten/ Dinkel', 'Gluten/ Spelt', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 7, 'Gluten/ Kamut', 'Gluten/ Kamut', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 8, 'Gluten/ Emmer', 'Gluten/ Emmer', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 9, 'Gluten/ Einkorn', 'Gluten/ Einkorn', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 10, 'Gluten/ Grünkern', 'Gluten/ Freekeh', 1) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 11, 'Krebstiere', 'Crustaceans', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 12, 'Eier', 'Eggs', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 13, 'Fisch', 'Fish', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 14, 'Erdnuss', 'Peanuts', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 15, 'Soja', 'Soy', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 16, 'Milch', 'Milk', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 17, 'Schalenfrüchte', 'Tree nuts (general)', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 18, 'Schalenfrüchte/ Mandeln', 'Tree nuts/ Almonds', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 19, 'Schalenfrüchte/ Haselnuss', 'Tree nuts/ Hazelnuts', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 20, 'Schalenfrüchte/ Walnuss', 'Tree nuts/ Walnuts', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 21, 'Schalenfrüchte/ Kaschunuss', 'Tree nuts/ Cashews', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 22, 'Schalenfrüchte/ Pecannuss', 'Tree nuts/ Pecans', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 23, 'Schalenfrüchte/ Paranuss', 'Tree nuts/ Brazil nuts', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 24, 'Schalenfrüchte/ Pistazie', 'Tree nuts/ Pistachios', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 25, 'Schalenfrüchte/ Macadamie-/ Queenslandnuss', 'Tree nuts/ Macadamia', 17) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 26, 'Sellerie', 'Celery', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 27, 'Senf', 'Mustard', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 28, 'Sesamsamen', 'Sesame seeds', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 29, 'Schwefeldioxid und Sulfit', 'Sulphur dioxide & sulphites', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 30, 'Lupine', 'Lupin', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;
INSERT INTO public.allergens (id, code, name_de, name_en, parent_code) VALUES (gen_random_uuid(), 31, 'Weichtiere', 'Molluscs', NULL) ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en, parent_code = EXCLUDED.parent_code;

-- ---------------------------------------------------------------------------
-- additives (from additives.json); code is integer
-- ---------------------------------------------------------------------------
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 101, 'mit Geschmacksverstärker', 'with flavour enhancer') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 102, 'mit Farbstoff', 'with colouring') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 103, 'gewachst', 'waxed') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 104, 'geschwärzt', 'blackened') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 105, 'mit Phosphat', 'with phosphate') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 106, 'mit Konservierungsstoff', 'with preservative') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 107, 'geschwefelt', 'sulphured') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 108, 'mit Antioxidationsmittel', 'with antioxidant') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 109, 'enthält eine Phenylalaninquelle', 'contains phenylalanine source') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 110, 'mit Süßungsmittel', 'with sweetener') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 111, 'mit einer Zuckerart und Süßungsmittel', 'with sugar and sweetener') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 112, 'Säuerungsmittel', 'acidifier') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 113, 'Säureregulator', 'acidity regulator') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 114, 'Aroma', 'flavouring') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 115, 'Emulgator', 'emulsifier') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 116, 'Verdickungsmittel', 'thickener') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 117, 'Schmelzsalz', 'emulsifying salt') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 118, 'chininhaltig', 'contains quinine') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 119, 'coffeinhaltig', 'contains caffeine') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 120, 'Backtriebmittel', 'raising agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 121, 'Geliermittel', 'gelling agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 122, 'modifizierte Stärke', 'modified starch') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 123, 'Stabilisator', 'stabiliser') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 124, 'Überzugsmittel', 'glazing agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 125, 'Schaumverhüter', 'anti-foaming agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 126, 'Trennmittel', 'anti-caking agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 127, 'Füllstoff', 'bulking agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 128, 'Festigungsmittel', 'firming agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 129, 'Mehlbehandlungsmittel', 'flour treatment agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 130, 'Treibgas', 'propellant') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 131, 'Schaummittel', 'foaming agent') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;
INSERT INTO public.additives (id, code, name_de, name_en) VALUES (gen_random_uuid(), 132, 'Feuchthaltemittel', 'humectant') ON CONFLICT (code) DO UPDATE SET name_de = EXCLUDED.name_de, name_en = EXCLUDED.name_en;

COMMIT;
