import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from "vite-plugin-pwa";
import path from "path";

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // Auto-update: new SW takes over on next page load (skip-waiting + clients-claim).
      registerType: "autoUpdate",
      // Static assets that should be served alongside the manifest. The icons
      // live in public/icons/ so Vite copies them to dist/icons/.
      includeAssets: ["icons/*.png", "favicon.ico"],
      manifest: {
        // `id` is the stable identifier for the installed app, separate from
        // `start_url`. Hard-coding it means the install survives even if we
        // ever change the start path (e.g. moving to "/kitchen/" once the
        // HTTPS proxy lands).
        id: "/voice-chef-kitchen",
        name: "Voice Chef Kitchen",
        short_name: "Voice Chef",
        description: "Voice-first AI cooking assistant",
        theme_color: "#0a0a0a",
        background_color: "#0a0a0a",
        display: "standalone",
        orientation: "any",
        start_url: "/",
        icons: [
          { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
          {
            src: "/icons/icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      workbox: {
        // Precache the app shell (HTML, JS, CSS, icons, manifest) so reload
        // works offline. globPatterns picks up everything Vite emits to dist/.
        globPatterns: ["**/*.{js,css,html,svg,png,ico,webmanifest}"],
        // SPA navigation fallback: any in-app route serves index.html from
        // cache. Excludes API/streaming endpoints which must hit the network.
        navigateFallback: "/index.html",
        navigateFallbackDenylist: [
          /^\/api/,
          /^\/agent/,
          /^\/stt/,
          /^\/wake/,
          /^\/uploads/,
          /^\/docs/,
          /^\/openapi\.json/,
          /^\/config\.js$/,
        ],
        runtimeCaching: [
          {
            // Stale-while-revalidate for the read-only catalog endpoints —
            // recipes and ingredients (including detail and autocomplete
            // subpaths). Cached responses serve immediately when offline or
            // on slow networks; online requests still hit the backend in the
            // background to keep the cache fresh on the next page view.
            // Workbox defaults to GET-only, so writes are unaffected.
            urlPattern: ({ url }: { url: URL }) =>
              /^\/api\/(recipes|ingredients)(\/|$)/.test(url.pathname),
            handler: "StaleWhileRevalidate" as const,
            options: {
              cacheName: "voice-chef-api-cache",
              expiration: {
                maxEntries: 500,
                maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
              },
              cacheableResponse: {
                // Don't cache 401/4xx — auth failures shouldn't poison the
                // cache and persist when the user logs in later.
                statuses: [0, 200],
              },
            },
          },
          {
            // Auth-sensitive, dynamic, streaming, runtime-generated — never
            // cache. Catches /api/auth, /api/uploads, /agent/*, /stt/*,
            // /wake/*, /uploads/*, and /config.js (the runtime-config script
            // generated by the kitchen-frontend container's entrypoint).
            urlPattern: ({ url }: { url: URL }) =>
              /^\/(api|agent|stt|wake|uploads)\//.test(url.pathname) ||
              url.pathname === "/config.js",
            handler: "NetworkOnly" as const,
          },
        ],
      },
      devOptions: {
        // Disable PWA in dev mode by default; flip to true when actively
        // testing the SW locally with `npm run dev`.
        enabled: false,
      },
    }),
  ],
  server: {
    host: true,
    port: 5174,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
