# This models were generated by group offline session of Dima, Maryna and Merctan
# Probably they are outdated. Here is only as a draft

from datetime import date, datetime
from decimal import Decimal
from typing import Optional
import datetime
import decimal
import uuid

from sqlalchemy import Boolean, CheckConstraint, Column, Date, DateTime, ForeignKeyConstraint, Index, Integer, Numeric, PrimaryKeyConstraint, String, Table, Text, UniqueConstraint, Uuid, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel

from app.models.user_models import Tenants, Users
from app.models.recipe_models import Recipes
Recipe = Recipes

class Additives(SQLModel, table=True):
    __table_args__ = (
        PrimaryKeyConstraint('id', name='additives_pkey'),
        UniqueConstraint('code', name='additives_code_key')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    code: int = Field(sa_column=Column('code', Integer, nullable=False))
    name_de: str = Field(sa_column=Column('name_de', String(255), nullable=False))
    name_en: Optional[str] = Field(default=None, sa_column=Column('name_en', String(255)))

    ingredient: list['Ingredients'] = Relationship(back_populates='additive', sa_relationship_kwargs={'secondary': 'ingredient_additives'})


class Allergens(SQLModel, table=True):
    __table_args__ = (
        PrimaryKeyConstraint('id', name='allergens_pkey'),
        UniqueConstraint('code', name='allergens_code_key')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    code: int = Field(sa_column=Column('code', Integer, nullable=False))
    name_de: str = Field(sa_column=Column('name_de', String(255), nullable=False))
    name_en: Optional[str] = Field(default=None, sa_column=Column('name_en', String(255)))
    parent_code: Optional[int] = Field(default=None, sa_column=Column('parent_code', Integer))

    ingredient: list['Ingredients'] = Relationship(back_populates='allergen', sa_relationship_kwargs={'secondary': 'ingredient_allergens'})


class AuditLogs(SQLModel, table=True):
    __tablename__ = 'audit_logs'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='audit_logs_pkey'),
        Index('idx_audit_logs_entity', 'entity', 'entity_id'),
        Index('idx_audit_logs_tenant', 'tenant_id', text('created_at DESC'))
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    tenant_id: uuid.UUID = Field(sa_column=Column('tenant_id', Uuid, nullable=False))
    actor_type: str = Field(sa_column=Column('actor_type', String(50), nullable=False))
    actor_id: uuid.UUID = Field(sa_column=Column('actor_id', Uuid, nullable=False))
    action: str = Field(sa_column=Column('action', String(50), nullable=False))
    entity: str = Field(sa_column=Column('entity', String(100), nullable=False))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
    entity_id: Optional[uuid.UUID] = Field(default=None, sa_column=Column('entity_id', Uuid))
    old_data: Optional[dict] = Field(default=None, sa_column=Column('old_data', JSONB))
    new_data: Optional[dict] = Field(default=None, sa_column=Column('new_data', JSONB))


class Units(SQLModel, table=True):
    __table_args__ = (
        CheckConstraint("unit_type::text = ANY (ARRAY['weight'::character varying, 'volume'::character varying, 'piece'::character varying, 'custom'::character varying]::text[])", name='valid_unit_type'),
        PrimaryKeyConstraint('id', name='units_pkey'),
        UniqueConstraint('code', name='units_code_key')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    code: str = Field(sa_column=Column('code', String(20), nullable=False))
    name_de: str = Field(sa_column=Column('name_de', String(100), nullable=False))
    unit_type: str = Field(sa_column=Column('unit_type', String(20), nullable=False))
    is_base: bool = Field(sa_column=Column('is_base', Boolean, nullable=False, server_default=text('false')))
    name_en: Optional[str] = Field(default=None, sa_column=Column('name_en', String(100)))
    grams_per_unit: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('grams_per_unit', Numeric))


class Agents(SQLModel, table=True):
    __table_args__ = (
        ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='agents_tenant_id_fkey'),
        PrimaryKeyConstraint('id', name='agents_pkey')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    tenant_id: uuid.UUID = Field(sa_column=Column('tenant_id', Uuid, nullable=False))
    agent_type: str = Field(sa_column=Column('agent_type', String(50), nullable=False))
    name: str = Field(sa_column=Column('name', String(255), nullable=False))
    capabilities: dict = Field(sa_column=Column('capabilities', JSONB, nullable=False, server_default=text("'[]'::jsonb")))
    is_active: bool = Field(sa_column=Column('is_active', Boolean, nullable=False, server_default=text('true')))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))

    tenant: 'Tenants' = Relationship(back_populates='agents')
    agent_interactions: list['AgentInteractions'] = Relationship(back_populates='agent')


class Categories(SQLModel, table=True):
    __table_args__ = (
        ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='categories_tenant_id_fkey'),
        PrimaryKeyConstraint('id', name='categories_pkey')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    name: str = Field(sa_column=Column('name', String(255), nullable=False))
    tenant_id: Optional[uuid.UUID] = Field(default=None, sa_column=Column('tenant_id', Uuid))

    tenant: Optional['Tenants'] = Relationship(back_populates='categories')
    recipe: list['Recipes'] = Relationship(back_populates='category', sa_relationship_kwargs={'secondary': 'recipe_categories'})


class Ingredients(SQLModel, table=True):
    __table_args__ = (
        ForeignKeyConstraint(['parent_id'], ['ingredients.id'], name='ingredients_parent_id_fkey'),
        ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='ingredients_tenant_id_fkey'),
        PrimaryKeyConstraint('id', name='ingredients_pkey'),
        Index('idx_ingredients_name', 'name'),
        Index('idx_ingredients_parent', 'parent_id'),
        Index('idx_ingredients_tenant', 'tenant_id')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    name: str = Field(sa_column=Column('name', String(255), nullable=False))
    source: str = Field(sa_column=Column('source', String(50), nullable=False, server_default=text("'standard'::character varying")))
    is_custom: bool = Field(sa_column=Column('is_custom', Boolean, nullable=False, server_default=text('false')))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
    updated_at: datetime.datetime = Field(sa_column=Column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
    tenant_id: Optional[uuid.UUID] = Field(default=None, sa_column=Column('tenant_id', Uuid))
    name_english: Optional[str] = Field(default=None, sa_column=Column('name_english', String(255)))
    bls_key: Optional[str] = Field(default=None, sa_column=Column('bls_key', String(50)))
    default_unit: Optional[str] = Field(default=None, sa_column=Column('default_unit', String(50)))
    parent_id: Optional[uuid.UUID] = Field(default=None, sa_column=Column('parent_id', Uuid))

    additive: list['Additives'] = Relationship(back_populates='ingredient', sa_relationship_kwargs={'secondary': 'ingredient_additives'})
    allergen: list['Allergens'] = Relationship(back_populates='ingredient', sa_relationship_kwargs={'secondary': 'ingredient_allergens'})
    parent: Optional['Ingredients'] = Relationship(back_populates='parent_reverse', sa_relationship_kwargs={'remote_side': '[Ingredients.id]'})
    parent_reverse: list['Ingredients'] = Relationship(back_populates='parent', sa_relationship_kwargs={'remote_side': '[Ingredients.parent_id]'})
    tenant: Optional['Tenants'] = Relationship(back_populates='ingredients')
    ingredient_nutrition: 'IngredientNutrition' = Relationship(back_populates='ingredient', sa_relationship_kwargs={'uselist': False})
    ingredient_prices: list['IngredientPrices'] = Relationship(back_populates='ingredient')
    ingredient_units: list['IngredientUnits'] = Relationship(back_populates='ingredient')
    recipe_ingredients: list['RecipeIngredients'] = Relationship(back_populates='ingredient')


class ShoppingLists(SQLModel, table=True):
    __tablename__ = 'shopping_lists'
    __table_args__ = (
        ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='shopping_lists_tenant_id_fkey'),
        PrimaryKeyConstraint('id', name='shopping_lists_pkey')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    tenant_id: uuid.UUID = Field(sa_column=Column('tenant_id', Uuid, nullable=False))
    name: str = Field(sa_column=Column('name', String(255), nullable=False, server_default=text("'Shopping List'::character varying")))
    is_active: bool = Field(sa_column=Column('is_active', Boolean, nullable=False, server_default=text('true')))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))

    tenant: 'Tenants' = Relationship(back_populates='shopping_lists')
    shopping_list_items: list['ShoppingListItems'] = Relationship(back_populates='list')


class Tags(SQLModel, table=True):
    __table_args__ = (
        ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='tags_tenant_id_fkey'),
        PrimaryKeyConstraint('id', name='tags_pkey')
    )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     name: str = Field(sa_column=mapped_column('name', Text, nullable=False))

#     recipe_tags: List['RecipeTags'] = Relationship(back_populates='tag')


# class Tenants(SQLModel, table=True):
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='tenants_pkey'),
#         UniqueConstraint('slug', name='tenants_slug_key'),
#         Index('ix_tenants_name', 'name'),
#         Index('ix_tenants_slug', 'slug', unique=True)
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid))
#     created_at: datetime = Field(sa_column=mapped_column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
#     updated_at: datetime = Field(sa_column=mapped_column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
#     name: str = Field(sa_column=mapped_column('name', String(255), nullable=False))
#     slug: str = Field(sa_column=mapped_column('slug', String(100), nullable=False))
#     is_active: bool = Field(sa_column=mapped_column('is_active', Boolean, nullable=False, server_default=text('true')))
#     settings: Optional[str] = Field(default=None, sa_column=mapped_column('settings', String))

#     ingredients: List['Ingredients'] = Relationship(back_populates='tenant')
#     users: List['Users'] = Relationship(back_populates='tenant')
#     recipes: List['Recipes'] = Relationship(back_populates='tenant')


class AgentInteractions(SQLModel, table=True):
    __tablename__ = 'agent_interactions'
    __table_args__ = (
        ForeignKeyConstraint(['agent_id'], ['agents.id'], name='agent_interactions_agent_id_fkey'),
        ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='agent_interactions_tenant_id_fkey'),
        PrimaryKeyConstraint('id', name='agent_interactions_pkey'),
        Index('idx_agent_interactions_agent', 'agent_id', text('created_at DESC')),
        Index('idx_agent_interactions_tenant', 'tenant_id', text('created_at DESC'))
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    tenant_id: uuid.UUID = Field(sa_column=Column('tenant_id', Uuid, nullable=False))
    agent_id: uuid.UUID = Field(sa_column=Column('agent_id', Uuid, nullable=False))
    source: str = Field(sa_column=Column('source', String(50), nullable=False))
    raw_input: str = Field(sa_column=Column('raw_input', Text, nullable=False))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
    parsed_intent: Optional[str] = Field(default=None, sa_column=Column('parsed_intent', String(255)))
    confidence_score: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('confidence_score', Numeric(3, 2)))
    tool_calls: Optional[dict] = Field(default=None, sa_column=Column('tool_calls', JSONB, server_default=text("'[]'::jsonb")))
    response_text: Optional[str] = Field(default=None, sa_column=Column('response_text', Text))
    latency_ms: Optional[int] = Field(default=None, sa_column=Column('latency_ms', Integer))
    error: Optional[str] = Field(default=None, sa_column=Column('error', Text))

    agent: 'Agents' = Relationship(back_populates='agent_interactions')
    tenant: 'Tenants' = Relationship(back_populates='agent_interactions')


t_ingredient_additives = Table(
    'ingredient_additives', SQLModel.metadata,
    Column('ingredient_id', Uuid, primary_key=True),
    Column('additive_id', Uuid, primary_key=True),
    ForeignKeyConstraint(['additive_id'], ['additives.id'], ondelete='CASCADE', name='ingredient_additives_additive_id_fkey'),
    ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='ingredient_additives_ingredient_id_fkey'),
    PrimaryKeyConstraint('ingredient_id', 'additive_id', name='ingredient_additives_pkey'),
    Index('idx_ing_additives_additive', 'additive_id')
)


t_ingredient_allergens = Table(
    'ingredient_allergens', SQLModel.metadata,
    Column('ingredient_id', Uuid, primary_key=True),
    Column('allergen_id', Uuid, primary_key=True),
    ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='CASCADE', name='ingredient_allergens_allergen_id_fkey'),
    ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='ingredient_allergens_ingredient_id_fkey'),
    PrimaryKeyConstraint('ingredient_id', 'allergen_id', name='ingredient_allergens_pkey'),
    Index('idx_ing_allergens_allergen', 'allergen_id')
)


class IngredientNutrition(SQLModel, table=True):
    __tablename__ = 'ingredient_nutrition'
    __table_args__ = (
        ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='ingredient_nutrition_ingredient_id_fkey'),
        PrimaryKeyConstraint('id', name='ingredient_nutrition_pkey'),
        UniqueConstraint('ingredient_id', name='ingredient_nutrition_ingredient_id_key')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    ingredient_id: uuid.UUID = Field(sa_column=Column('ingredient_id', Uuid, nullable=False))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
    updated_at: datetime.datetime = Field(sa_column=Column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
    energy_kj: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('energy_kj', Numeric))
    energy_kcal: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('energy_kcal', Numeric))
    fat: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('fat', Numeric))
    saturates: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('saturates', Numeric))
    carbs: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('carbs', Numeric))
    sugars: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('sugars', Numeric))
    protein: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('protein', Numeric))
    fiber: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('fiber', Numeric))
    salt: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('salt', Numeric))
    alcohol: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('alcohol', Numeric))
    water: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('water', Numeric))

    ingredient: 'Ingredients' = Relationship(back_populates='ingredient_nutrition')


# class RecipeCategories(SQLModel, table=True):
#     __tablename__ = 'recipe_categories'
#     __table_args__ = (
#         ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE', name='recipe_categories_category_id_fkey'),
#         PrimaryKeyConstraint('recipe_id', 'category_id', name='recipe_categories_pkey'),
#         Index('idx_recipe_cat_category', 'category_id')
#     )

#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     category_id: UUID = Field(sa_column=mapped_column('category_id', Uuid, nullable=False))

#     category: Optional['Categories'] = Relationship(back_populates='recipe_categories')


# class RecipeNutrition(SQLModel, table=True):
#     __tablename__ = 'recipe_nutrition'
#     __table_args__ = (
#         ForeignKeyConstraint(['nutrition_id'], ['nutrition_facts.id'], ondelete='CASCADE', name='recipe_nutrition_nutrition_id_fkey'),
#         PrimaryKeyConstraint('recipe_id', name='recipe_nutrition_pkey'),
#         Index('idx_recipe_nutrition_nutrition', 'nutrition_id')
#     )

#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid))
#     nutrition_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('nutrition_id', Uuid))
#     updated_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('updated_at', DateTime(True), server_default=text('now()')))

#     nutrition: Optional['NutritionFacts'] = Relationship(back_populates='recipe_nutrition')


# class RecipeTags(SQLModel, table=True):
#     __tablename__ = 'recipe_tags'
#     __table_args__ = (
#         ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE', name='recipe_tags_tag_id_fkey'),
#         PrimaryKeyConstraint('recipe_id', 'tag_id', name='recipe_tags_pkey'),
#         Index('idx_recipe_tags_tag', 'tag_id')
#     )

#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     tag_id: UUID = Field(sa_column=mapped_column('tag_id', Uuid, nullable=False))

#     tag: Optional['Tags'] = Relationship(back_populates='recipe_tags')


# class Users(SQLModel, table=True):
#     __table_args__ = (
#         ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='users_tenant_id_fkey'),
#         PrimaryKeyConstraint('id', name='users_pkey'),
#         UniqueConstraint('email', name='users_email_key'),
#         Index('ix_users_email', 'email', unique=True)
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid))
#     created_at: datetime = Field(sa_column=mapped_column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
#     updated_at: datetime = Field(sa_column=mapped_column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
#     email: str = Field(sa_column=mapped_column('email', String(255), nullable=False))
#     password_hash: str = Field(sa_column=mapped_column('password_hash', String(255), nullable=False))
#     role: str = Field(sa_column=mapped_column('role', String(50), nullable=False, server_default=text("'editor'::character varying")))
#     is_active: bool = Field(sa_column=mapped_column('is_active', Boolean, nullable=False, server_default=text('true')))
#     tenant_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('tenant_id', Uuid))

#     tenant: Optional['Tenants'] = Relationship(back_populates='users')
#     recipes: List['Recipes'] = Relationship(back_populates='users')


class IngredientUnits(SQLModel, table=True):
    __tablename__ = 'ingredient_units'
    __table_args__ = (
        CheckConstraint('grams_per_unit > 0::numeric', name='ingredient_units_grams_per_unit_positive'),
        ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='ingredient_units_ingredient_id_fkey'),
        PrimaryKeyConstraint('id', name='ingredient_units_pkey'),
        UniqueConstraint('ingredient_id', 'unit_code', name='uq_ingredient_unit'),
        Index('idx_ingredient_units_ingredient', 'ingredient_id')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    ingredient_id: uuid.UUID = Field(sa_column=Column('ingredient_id', Uuid, nullable=False))
    unit_code: str = Field(sa_column=Column('unit_code', String(20), nullable=False))
    grams_per_unit: decimal.Decimal = Field(sa_column=Column('grams_per_unit', Numeric, nullable=False))
    label: Optional[str] = Field(default=None, sa_column=Column('label', String(100)))

    ingredient: 'Ingredients' = Relationship(back_populates='ingredient_units')


class ShoppingListItems(SQLModel, table=True):
    __tablename__ = 'shopping_list_items'
    __table_args__ = (
        CheckConstraint('quantity_grams IS NULL OR quantity_grams >= 0::numeric', name='shopping_list_items_quantity_grams_non_negative'),
        ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ondelete='CASCADE', name='shopping_list_items_list_id_fkey'),
        PrimaryKeyConstraint('id', name='shopping_list_items_pkey'),
        Index('idx_shopping_items_list', 'list_id')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    list_id: uuid.UUID = Field(sa_column=Column('list_id', Uuid, nullable=False))
    name: str = Field(sa_column=Column('name', String(255), nullable=False))
    is_checked: bool = Field(sa_column=Column('is_checked', Boolean, nullable=False, server_default=text('false')))
    sort_order: int = Field(sa_column=Column('sort_order', Integer, nullable=False, server_default=text('0')))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
    quantity: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('quantity', Numeric))
    unit: Optional[str] = Field(default=None, sa_column=Column('unit', String(50)))
    quantity_grams: Optional[decimal.Decimal] = Field(default=None, sa_column=Column('quantity_grams', Numeric))

    list: 'ShoppingLists' = Relationship(back_populates='shopping_list_items')


class TaskItems(SQLModel, table=True):
    __tablename__ = 'task_items'
    __table_args__ = (
        CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'done'::character varying]::text[])", name='valid_task_status'),
        ForeignKeyConstraint(['list_id'], ['task_lists.id'], ondelete='CASCADE', name='task_items_list_id_fkey'),
        PrimaryKeyConstraint('id', name='task_items_pkey'),
        Index('idx_task_items_list', 'list_id')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    list_id: uuid.UUID = Field(sa_column=Column('list_id', Uuid, nullable=False))
    title: str = Field(sa_column=Column('title', String(500), nullable=False))
    status: str = Field(sa_column=Column('status', String(50), nullable=False, server_default=text("'pending'::character varying")))
    sort_order: int = Field(sa_column=Column('sort_order', Integer, nullable=False, server_default=text('0')))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))

#     ingredient: Optional['Ingredients'] = Relationship(back_populates='ingredient_prices')

class Recipe(SQLModel, table=True):
    __tablename__ = "recipes"

    # Primary key
    id: UUID = Field(default_factory=uuid4, primary_key=True)

    # Core fields
    name: str = Field(max_length=255, index=True)
    status: str = Field(default="draft", max_length=50)

    # Timestamps
    created_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False, server_default=text("now()"))
    )
    updated_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=text("now()"),
            onupdate=text("now()"),
        )
    )

    # Foreign keys
    tenant_id: Optional[UUID] = Field(default=None, foreign_key="tenants.id")
    created_by: Optional[UUID] = Field(default=None, foreign_key="users.id")

    # Text fields
    description: Optional[str] = None
    description_short: Optional[str] = None
    instructions: Optional[str] = None
    notes: Optional[str] = None
    notes_instructions: Optional[str] = None
    serving_recommendation: Optional[str] = None
    side_dishes: Optional[str] = None
    storage_text: Optional[str] = None
    origin_fish: Optional[str] = None
    origin_location: Optional[str] = None
    devices: Optional[str] = None
    utensils: Optional[str] = None
    packaging: Optional[str] = None
    packaging_material: Optional[str] = None
    # branch_ids: Optional[str] = None
    ingredient_list_custom: Optional[str] = None
    # ingredient_list_product_pass: Optional[str] = None
    allergene_source: Optional[str] = None

    # Numeric fields
    yield_amount: Optional[Decimal] = None
    reduction_factor: Optional[Decimal] = Field(default=None, index=True)
    eigene_menge: Optional[Decimal] = None
    net_weight: Optional[Decimal] = None
    fill_weight: Optional[Decimal] = None
    fill_quantity: Optional[Decimal] = None
    drained_weight: Optional[Decimal] = None
    total_weight: Optional[Decimal] = None
    portion_weight: Optional[Decimal] = None
    margin: Optional[Decimal] = None
    nutri_score_veg_fruits: Optional[Decimal] = None
    preference_nutri_value: Optional[Decimal] = None

    # Strings
    yield_unit: Optional[str] = Field(default=None, max_length=50)
    recipe_number: Optional[str] = Field(default=None, max_length=100)
    batch_number: Optional[str] = Field(default=None, max_length=100, index=True)
    storage_temperature: Optional[str] = Field(default=None, max_length=50)
    labor_effort: Optional[str] = Field(default=None, max_length=50)
    nutri_score_category: Optional[str] = Field(default=None, max_length=10)
    unit_measure: Optional[str] = Field(default=None, max_length=50)
    unit_serving: Optional[str] = Field(default=None, max_length=50)

    # Booleans
    portion_by_weight: bool = Field(default=False)
    mise_en_place_display: bool = Field(default=True)
    is_component: bool = Field(default=False)

    # Dates
    production_date: Optional[date] = None
    use_by_date: Optional[date] = None
    expiry_date: Optional[date] = None

# class RecipeIngredients(SQLModel, table=True):
#     __tablename__ = 'recipe_ingredients'
#     __table_args__ = (
#         ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='recipe_ingredients_ingredient_id_fkey'),
#         ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE', name='recipe_ingredients_recipe_id_fkey'),
#         PrimaryKeyConstraint('id', name='recipe_ingredients_pkey'),
#         UniqueConstraint('recipe_id', 'ingredient_id', 'sort_order', name='uq_recipe_ingredient_order'),
#         Index('ix_recipe_ingredients_ingredient_id', 'ingredient_id'),
#         Index('ix_recipe_ingredients_recipe_id', 'recipe_id'),
#         Index('ix_recipe_ingredients_sort_order', 'sort_order')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid))
#     created_at: datetime = Field(sa_column=mapped_column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
#     updated_at: datetime = Field(sa_column=mapped_column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     ingredient_id: UUID = Field(sa_column=mapped_column('ingredient_id', Uuid, nullable=False))
#     sort_order: int = Field(sa_column=mapped_column('sort_order', Integer, nullable=False, server_default=text('0')))
#     quantity: Optional[Decimal] = Field(default=None, sa_column=mapped_column('quantity', Numeric(10, 4)))
#     unit: Optional[str] = Field(default=None, sa_column=mapped_column('unit', String(50)))
#     preparation: Optional[str] = Field(default=None, sa_column=mapped_column('preparation', String(255)))
#     quid: Optional[Decimal] = Field(default=None, sa_column=mapped_column('quid', Numeric(10, 4)))
#     item_type: Optional[str] = Field(default=None, sa_column=mapped_column('item_type', String(50)))

#     ingredient: Optional['Ingredients'] = Relationship(back_populates='recipe_ingredients')
#     recipe: Optional['Recipes'] = Relationship(back_populates='recipe_ingredients')


# class RecipePhotos(SQLModel, table=True):
#     __tablename__ = 'recipe_photos'
#     __table_args__ = (
#         ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE', name='recipe_photos_recipe_id_fkey'),
#         PrimaryKeyConstraint('id', name='recipe_photos_pkey'),
#         Index('idx_recipe_photos_recipe', 'recipe_id')
#     )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('gen_random_uuid()')))
    recipe_id: uuid.UUID = Field(sa_column=Column('recipe_id', Uuid, nullable=False))
    version: int = Field(sa_column=Column('version', Integer, nullable=False))
    data: dict = Field(sa_column=Column('data', JSONB, nullable=False))
    created_at: datetime.datetime = Field(sa_column=Column('created_at', DateTime(True), nullable=False, server_default=text('now()')))

    recipe: 'Recipes' = Relationship(back_populates='recipe_versions')

