# This models were generated by group offline session of Dima, Maryna and Merctan
# Probably they are outdated. Here is only as a draft

from datetime import date, datetime
from decimal import Decimal
from typing import Optional
import uuid
from uuid import UUID, uuid4

from sqlalchemy import PrimaryKeyConstraint, text, DateTime, Column
from sqlalchemy import Boolean, CheckConstraint, Column, Date, DateTime, ForeignKeyConstraint, Index, Integer, LargeBinary, Numeric, String, Text, UniqueConstraint, Uuid
from sqlmodel import Field, SQLModel, Relationship


class Additives(SQLModel, table=True):
    __table_args__ = (
        PrimaryKeyConstraint('id', name='additives_pkey'),
        UniqueConstraint('code', name='additives_code_key'),
        Index('idx_additives_code', 'code')
    )

    id: uuid.UUID = Field(sa_column=Column('id', Uuid, primary_key=True, server_default=text('uuid_generate_v4()')))
    code: str = Field(sa_column=Column('code', Text, nullable=False))
    name: str = Field(sa_column=Column('name', Text, nullable=False))

    ingredient_additives: list['IngredientAdditives'] = Relationship(back_populates='additive')

# class Allergens(SQLModel, table=True):
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='allergens_pkey'),
#         UniqueConstraint('code', name='allergens_code_key'),
#         Index('idx_allergens_code', 'code')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     code: str = Field(sa_column=mapped_column('code', Text, nullable=False))
#     name: str = Field(sa_column=mapped_column('name', Text, nullable=False))

#     ingredient_allergens: List['IngredientAllergens'] = Relationship(back_populates='allergen')


# class AuditLogs(SQLModel, table=True):
#     __tablename__ = 'audit_logs'
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='audit_logs_pkey'),
#         Index('idx_audit_logs_created', 'created_at'),
#         Index('idx_audit_logs_entity', 'entity', 'entity_id'),
#         Index('idx_audit_logs_user', 'user_id')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     action: str = Field(sa_column=mapped_column('action', Text, nullable=False))
#     entity: str = Field(sa_column=mapped_column('entity', Text, nullable=False))
#     user_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('user_id', Uuid))
#     entity_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('entity_id', Uuid))
#     created_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('created_at', DateTime(True), server_default=text('now()')))


# class Categories(SQLModel, table=True):
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='categories_pkey'),
#         Index('idx_categories_name', 'name')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     name: str = Field(sa_column=mapped_column('name', Text, nullable=False))

#     recipe_categories: List['RecipeCategories'] = Relationship(back_populates='category')


# class Files(SQLModel, table=True):
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='files_pkey'),
#         Index('idx_files_recipe', 'recipe_id')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     file_type: str = Field(sa_column=mapped_column('file_type', Text, nullable=False))
#     uri: str = Field(sa_column=mapped_column('uri', Text, nullable=False))
#     recipe_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('recipe_id', Uuid))
#     created_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('created_at', DateTime(True), server_default=text('now()')))


# class Heroes(SQLModel, table=True):
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='heroes_pkey'),
#         UniqueConstraint('email', name='heroes_email_key'),
#         UniqueConstraint('username', name='heroes_username_key')
#     )

#     id: Optional[int] = Field(default=None, sa_column=mapped_column('id', Integer))
#     username: str = Field(sa_column=mapped_column('username', String, nullable=False))
#     email: str = Field(sa_column=mapped_column('email', String, nullable=False))
#     firstname: str = Field(sa_column=mapped_column('firstname', String, nullable=False))
#     lastname: str = Field(sa_column=mapped_column('lastname', String, nullable=False))


# class NutritionFacts(SQLModel, table=True):
#     __tablename__ = 'nutrition_facts'
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='nutrition_facts_pkey'),
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     energy_kj: Optional[Decimal] = Field(default=None, sa_column=mapped_column('energy_kj', Numeric))
#     energy_kcal: Optional[Decimal] = Field(default=None, sa_column=mapped_column('energy_kcal', Numeric))
#     fat: Optional[Decimal] = Field(default=None, sa_column=mapped_column('fat', Numeric))
#     saturates: Optional[Decimal] = Field(default=None, sa_column=mapped_column('saturates', Numeric))
#     carbs: Optional[Decimal] = Field(default=None, sa_column=mapped_column('carbs', Numeric))
#     sugars: Optional[Decimal] = Field(default=None, sa_column=mapped_column('sugars', Numeric))
#     protein: Optional[Decimal] = Field(default=None, sa_column=mapped_column('protein', Numeric))
#     salt: Optional[Decimal] = Field(default=None, sa_column=mapped_column('salt', Numeric))

#     recipe_nutrition: List['RecipeNutrition'] = Relationship(back_populates='nutrition')


# class RecipeVersions(SQLModel, table=True):
#     __tablename__ = 'recipe_versions'
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='recipe_versions_pkey'),
#         Index('idx_recipe_versions_data', 'data'),
#         Index('idx_recipe_versions_recipe', 'recipe_id')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     version: int = Field(sa_column=mapped_column('version', Integer, nullable=False))
#     data: dict = Field(sa_column=mapped_column('data', JSONB, nullable=False))
#     recipe_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('recipe_id', Uuid))
#     created_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('created_at', DateTime(True), server_default=text('now()')))


# class Tags(SQLModel, table=True):
#     __table_args__ = (
#         PrimaryKeyConstraint('id', name='tags_pkey'),
#         Index('idx_tags_name', 'name')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     name: str = Field(sa_column=mapped_column('name', Text, nullable=False))

#     recipe_tags: List['RecipeTags'] = Relationship(back_populates='tag')


class IngredientAdditives(SQLModel, table=True):
    __tablename__ = 'ingredient_additives'
    __table_args__ = (
        ForeignKeyConstraint(['additive_id'], ['additives.id'], ondelete='CASCADE', name='ingredient_additives_additive_id_fkey'),
        PrimaryKeyConstraint('ingredient_id', 'additive_id', name='ingredient_additives_pkey'),
        Index('idx_ing_additives_additive', 'additive_id')
    )

    ingredient_id: uuid.UUID = Field(sa_column=Column('ingredient_id', Uuid, primary_key=True))
    additive_id: uuid.UUID = Field(sa_column=Column('additive_id', Uuid, primary_key=True))

    additive: 'Additives' = Relationship(back_populates='ingredient_additives')


# class IngredientAllergens(SQLModel, table=True):
#     __tablename__ = 'ingredient_allergens'
#     __table_args__ = (
#         ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='CASCADE', name='ingredient_allergens_allergen_id_fkey'),
#         PrimaryKeyConstraint('ingredient_id', 'allergen_id', name='ingredient_allergens_pkey'),
#         Index('idx_ing_allergens_allergen', 'allergen_id')
#     )

#     ingredient_id: UUID = Field(sa_column=mapped_column('ingredient_id', Uuid, nullable=False))
#     allergen_id: UUID = Field(sa_column=mapped_column('allergen_id', Uuid, nullable=False))

#     allergen: Optional['Allergens'] = Relationship(back_populates='ingredient_allergens')


# class Ingredients(SQLModel, table=True):
#     __table_args__ = (
#         ForeignKeyConstraint(['parent_id'], ['ingredients.id'], name='ingredients_parent_id_fkey'),
#         ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='ingredients_tenant_id_fkey'),
#         PrimaryKeyConstraint('id', name='ingredients_pkey'),
#         Index('idx_ingredients_parent_id', 'parent_id'),
#         Index('idx_ingredients_usage_count', 'usage_count'),
#         Index('ix_ingredients_name', 'name')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid))
#     created_at: datetime = Field(sa_column=mapped_column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
#     updated_at: datetime = Field(sa_column=mapped_column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
#     name: str = Field(sa_column=mapped_column('name', String(255), nullable=False))
#     tenant_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('tenant_id', Uuid))
#     default_unit: Optional[str] = Field(default=None, sa_column=mapped_column('default_unit', String(50)))
#     nutrition_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('nutrition_id', Uuid))
#     usage_count: Optional[int] = Field(default=None, sa_column=mapped_column('usage_count', Integer, server_default=text('0')))
#     recipe_count: Optional[int] = Field(default=None, sa_column=mapped_column('recipe_count', Integer, server_default=text('0')))
#     ingredient_type: Optional[str] = Field(default=None, sa_column=mapped_column('ingredient_type', String(50)))
#     bls_key: Optional[str] = Field(default=None, sa_column=mapped_column('bls_key', String(100)))
#     is_custom: Optional[bool] = Field(default=None, sa_column=mapped_column('is_custom', Boolean, server_default=text('false')))
#     has_parent: Optional[bool] = Field(default=None, sa_column=mapped_column('has_parent', Boolean, server_default=text('false')))
#     parent_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('parent_id', Uuid))
#     initial_recipe_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('initial_recipe_id', Uuid))

#     parent: Optional['Ingredients'] = Relationship(back_populates='parent_reverse')
#     parent_reverse: List['Ingredients'] = Relationship(back_populates='parent')
#     tenant: Optional['Tenants'] = Relationship(back_populates='ingredients')
#     ingredient_nutrition: Optional['IngredientNutrition'] = Relationship(sa_relationship_kwargs={'uselist': False}, back_populates='ingredient')
#     ingredient_prices: List['IngredientPrices'] = Relationship(back_populates='ingredient')
#     recipe_ingredients: List['RecipeIngredients'] = Relationship(back_populates='ingredient')


# class RecipeCategories(SQLModel, table=True):
#     __tablename__ = 'recipe_categories'
#     __table_args__ = (
#         ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE', name='recipe_categories_category_id_fkey'),
#         PrimaryKeyConstraint('recipe_id', 'category_id', name='recipe_categories_pkey'),
#         Index('idx_recipe_cat_category', 'category_id')
#     )

#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     category_id: UUID = Field(sa_column=mapped_column('category_id', Uuid, nullable=False))

#     category: Optional['Categories'] = Relationship(back_populates='recipe_categories')


# class RecipeNutrition(SQLModel, table=True):
#     __tablename__ = 'recipe_nutrition'
#     __table_args__ = (
#         ForeignKeyConstraint(['nutrition_id'], ['nutrition_facts.id'], ondelete='CASCADE', name='recipe_nutrition_nutrition_id_fkey'),
#         PrimaryKeyConstraint('recipe_id', name='recipe_nutrition_pkey'),
#         Index('idx_recipe_nutrition_nutrition', 'nutrition_id')
#     )

#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid))
#     nutrition_id: Optional[UUID] = Field(default=None, sa_column=mapped_column('nutrition_id', Uuid))
#     updated_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('updated_at', DateTime(True), server_default=text('now()')))

#     nutrition: Optional['NutritionFacts'] = Relationship(back_populates='recipe_nutrition')


# class RecipeTags(SQLModel, table=True):
#     __tablename__ = 'recipe_tags'
#     __table_args__ = (
#         ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE', name='recipe_tags_tag_id_fkey'),
#         PrimaryKeyConstraint('recipe_id', 'tag_id', name='recipe_tags_pkey'),
#         Index('idx_recipe_tags_tag', 'tag_id')
#     )

#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     tag_id: UUID = Field(sa_column=mapped_column('tag_id', Uuid, nullable=False))

#     tag: Optional['Tags'] = Relationship(back_populates='recipe_tags')


# class IngredientNutrition(SQLModel, table=True):
#     __tablename__ = 'ingredient_nutrition'
#     __table_args__ = (
#         ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='ingredient_nutrition_ingredient_id_fkey'),
#         PrimaryKeyConstraint('id', name='ingredient_nutrition_pkey'),
#         UniqueConstraint('ingredient_id', name='ingredient_nutrition_ingredient_id_key')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('gen_random_uuid()')))
#     ingredient_id: UUID = Field(sa_column=mapped_column('ingredient_id', Uuid, nullable=False))
#     energy_kj: Optional[Decimal] = Field(default=None, sa_column=mapped_column('energy_kj', Numeric(10, 2)))
#     energy_kcal: Optional[Decimal] = Field(default=None, sa_column=mapped_column('energy_kcal', Numeric(10, 2)))
#     carbs: Optional[Decimal] = Field(default=None, sa_column=mapped_column('carbs', Numeric(10, 2)))
#     protein: Optional[Decimal] = Field(default=None, sa_column=mapped_column('protein', Numeric(10, 2)))
#     fat: Optional[Decimal] = Field(default=None, sa_column=mapped_column('fat', Numeric(10, 2)))
#     sugars: Optional[Decimal] = Field(default=None, sa_column=mapped_column('sugars', Numeric(10, 2)))
#     fiber: Optional[Decimal] = Field(default=None, sa_column=mapped_column('fiber', Numeric(10, 2)))
#     saturates: Optional[Decimal] = Field(default=None, sa_column=mapped_column('saturates', Numeric(10, 2)))
#     salt: Optional[Decimal] = Field(default=None, sa_column=mapped_column('salt', Numeric(10, 2)))
#     created_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('created_at', DateTime(True), server_default=text('now()')))
#     updated_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('updated_at', DateTime(True), server_default=text('now()')))
#     alcohol: Optional[Decimal] = Field(default=None, sa_column=mapped_column('alcohol', Numeric(10, 3)))
#     water: Optional[Decimal] = Field(default=None, sa_column=mapped_column('water', Numeric(10, 3)))

#     ingredient: Optional['Ingredients'] = Relationship(back_populates='ingredient_nutrition')


# class IngredientPrices(SQLModel, table=True):
#     __tablename__ = 'ingredient_prices'
#     __table_args__ = (
#         ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='ingredient_prices_ingredient_id_fkey'),
#         PrimaryKeyConstraint('id', name='ingredient_prices_pkey'),
#         UniqueConstraint('ingredient_id', 'supplier_id', name='ingredient_prices_ingredient_id_supplier_id_key'),
#         Index('idx_ingredient_prices_ingredient', 'ingredient_id')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     ingredient_id: UUID = Field(sa_column=mapped_column('ingredient_id', Uuid, nullable=False))
#     price_per_unit: Optional[Decimal] = Field(default=None, sa_column=mapped_column('price_per_unit', Numeric(10, 2)))
#     currency: Optional[str] = Field(default=None, sa_column=mapped_column('currency', String(3), server_default=text("'EUR'::character varying")))
#     unit: Optional[str] = Field(default=None, sa_column=mapped_column('unit', String(50)))
#     supplier_id: Optional[str] = Field(default=None, sa_column=mapped_column('supplier_id', String(100)))
#     supplier_name: Optional[str] = Field(default=None, sa_column=mapped_column('supplier_name', String(255)))
#     article_number: Optional[str] = Field(default=None, sa_column=mapped_column('article_number', String(100)))
#     created_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('created_at', DateTime(True), server_default=text('now()')))
#     updated_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('updated_at', DateTime(True), server_default=text('now()')))

#     ingredient: Optional['Ingredients'] = Relationship(back_populates='ingredient_prices')


# class RecipeIngredients(SQLModel, table=True):
#     __tablename__ = 'recipe_ingredients'
#     __table_args__ = (
#         ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE', name='recipe_ingredients_ingredient_id_fkey'),
#         ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE', name='recipe_ingredients_recipe_id_fkey'),
#         PrimaryKeyConstraint('id', name='recipe_ingredients_pkey'),
#         UniqueConstraint('recipe_id', 'ingredient_id', 'sort_order', name='uq_recipe_ingredient_order'),
#         Index('ix_recipe_ingredients_ingredient_id', 'ingredient_id'),
#         Index('ix_recipe_ingredients_recipe_id', 'recipe_id'),
#         Index('ix_recipe_ingredients_sort_order', 'sort_order')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid))
#     created_at: datetime = Field(sa_column=mapped_column('created_at', DateTime(True), nullable=False, server_default=text('now()')))
#     updated_at: datetime = Field(sa_column=mapped_column('updated_at', DateTime(True), nullable=False, server_default=text('now()')))
#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     ingredient_id: UUID = Field(sa_column=mapped_column('ingredient_id', Uuid, nullable=False))
#     sort_order: int = Field(sa_column=mapped_column('sort_order', Integer, nullable=False, server_default=text('0')))
#     quantity: Optional[Decimal] = Field(default=None, sa_column=mapped_column('quantity', Numeric(10, 4)))
#     unit: Optional[str] = Field(default=None, sa_column=mapped_column('unit', String(50)))
#     preparation: Optional[str] = Field(default=None, sa_column=mapped_column('preparation', String(255)))
#     quid: Optional[Decimal] = Field(default=None, sa_column=mapped_column('quid', Numeric(10, 4)))
#     item_type: Optional[str] = Field(default=None, sa_column=mapped_column('item_type', String(50)))

#     ingredient: Optional['Ingredients'] = Relationship(back_populates='recipe_ingredients')
#     recipe: Optional['Recipes'] = Relationship(back_populates='recipe_ingredients')


# class RecipePhotos(SQLModel, table=True):
#     __tablename__ = 'recipe_photos'
#     __table_args__ = (
#         ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE', name='recipe_photos_recipe_id_fkey'),
#         PrimaryKeyConstraint('id', name='recipe_photos_pkey'),
#         Index('idx_recipe_photos_recipe', 'recipe_id')
#     )

#     id: UUID = Field(sa_column=mapped_column('id', Uuid, server_default=text('uuid_generate_v4()')))
#     recipe_id: UUID = Field(sa_column=mapped_column('recipe_id', Uuid, nullable=False))
#     photo_url: Optional[str] = Field(default=None, sa_column=mapped_column('photo_url', Text))
#     photo_data: Optional[bytes] = Field(default=None, sa_column=mapped_column('photo_data', LargeBinary))
#     photo_type: Optional[str] = Field(default=None, sa_column=mapped_column('photo_type', String(50)))
#     is_primary: Optional[bool] = Field(default=None, sa_column=mapped_column('is_primary', Boolean, server_default=text('false')))
#     created_at: Optional[datetime] = Field(default=None, sa_column=mapped_column('created_at', DateTime(True), server_default=text('now()')))

#     recipe: Optional['Recipes'] = Relationship(back_populates='recipe_photos')
